# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build:
    cmds:
        - cmd: cl file.cpp main.cpp -o main.exe
          platforms: [windows]
        - cmd: g++ file.cpp main.cpp -o main
          platforms: [linux]

  run:
   deps: [build]
   cmds:
        - cmd: ./main.exe {{.CLI_ARGS}}
          platforms: [windows]
        - cmd: ./main {{.CLI_ARGS}}
          platforms: [linux]
