# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  cmake:
    cmds:
        - cmd: cmake -G "Ninja" -B build
  build:
    cmds:
        - cmd: cmake --build build

  run:
   deps: [build]
   cmds:
        - cmd: ./build/main.exe {{.CLI_ARGS}}
          platforms: [windows]
        - cmd: ./build/main {{.CLI_ARGS}}
          platforms: [linux]

  test:
   deps: [build]
   cmds:
        - cmd: ./build/main.exe asm/many_reg_mov
          platforms: [windows]
        - cmd: ./build/main asm/mor_mov
          platforms: [linux]
